language: java
matrix:
  include:
    - os: osx
      osx_image: xcode11
      install:
        - curl -s "https://get.sdkman.io" | bash
        - source ~/.bash_profile
        - sdk install kscript
        - sdk install gradle
        - sdk install kotlin
        - npm install -g danger@7.1.4
      script:
        - make install
        - gradle danger-kotlin-library:test
        - DEBUG='*' danger-kotlin ci
    - os: linux
      sudo: required
      dist: trusty
      install:
        - curl -s "https://get.sdkman.io" | bash
        - source ~/.bash_profile
        - sdk install kscript
        - sdk install gradle
        - sdk install kotlin
        - npm install -g danger@7.1.4
        - sudo chmod -R a+rwx /usr/local/
      script:
        - make install
        - gradle danger-kotlin-library:test
        - DEBUG='*' danger-kotlin ci
